services:
  webapi:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    container_name: webapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - WebAPI/.env.docker
    depends_on:
      - db
    networks:
      - backend

  bot:
    build:
      context: .
      dockerfile: Bot/Dockerfile
    container_name: bot
    env_file:
      - Bot/.env.docker
    depends_on:
      - db
      - webapi
    networks:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=telegram_bot_db
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
